# -*- coding: utf-8 -*-
"""MRI Image Segmentation - A study on Kaggle Compeition Data - Shayan Rokhva.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14hu52Mf7uj8FdBfJuHOU3y3VtUjyNee2

#  <font color='#FFE15D'><b>💎 MRI Image Segmentation on Kaggle Competition Data🔬</b></font>

# <font color='#FFE23D'><b>**Shayan Rokhva - 40266331003**

## 🔴 **Environment Setup**

### 🟠 **Connecting Colab to the local host (PC or laptop):**

`jupyter notebook --NotebookApp.allow_origin='https://colab.research.google.com' --port=4000 --NotebookApp.port_retries=0`

### 🟠 **Install torchmetrics for further evaluation**
"""

!pip install -q torchmetrics

"""### 🟠 **Install `portalocker`**"""

!pip install -q portalocker>=2.0.0

"""### 🟠 **Install `wandb`**"""

!pip install wandb

"""### ⚠️ **Don't forget to restart the runtime!**
We should do it every single time so that the models and parameters will be initialized again and no previous knowledge will be transfered**

## 🔴 **Import Libs**
"""

import os
import sys
import time
import random
import tqdm
from glob import glob
from typing import Any, Callable, Dict, List, Optional, Tuple

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from PIL import Image
import cv2

import torch
from torch import nn
from torch.nn import functional as F
from torch.utils.data import DataLoader, Dataset, random_split, ConcatDataset
from torch import optim

import torchvision
from torchvision import transforms
import torchvision.transforms.functional as F
from torchvision.datasets import VisionDataset
from torchvision.transforms import v2
from torchvision import tv_tensors

import segmentation_models_pytorch as smp

import torchmetrics as tm
from torchmetrics.aggregation import MeanMetric
from torchmetrics import Dice

!python --version

# Check versions for consistency

for lib in [np, torch, torchvision, tm, tqdm, smp]:
  print(lib.__name__, '-->', lib.__version__)

# sys.path

"""## 🔴 **Utils**"""

# fucntion for counting parameters
def num_trainable_params(model):
  nums = sum(p.numel() for p in model.parameters() if p.requires_grad)/1e6    # in million
  return nums

# Fixing random seeds for reproducible results.

def set_seed(seed):
  np.random.seed(seed)
  torch.manual_seed(seed)
  if torch.cuda.is_available():
      torch.cuda.manual_seed(seed)
      # torch.cuda.manual_seed_all(seed)

      # torch.backends.cudnn.deterministic = True
      # torch.backends.cudnn.benchmark = False

"""## 🔴 **Arguments**"""

# Let's have all the important hyperparameters in one place
seed = 8
wandb_enable = False
root = 'data'
batch_size = 32
backbone = 'efficientnet-b1'                   # Good becuase it is both lightweight and also goood acc. Efficient
num_classes = 3
classes = ['large_bowel', 'small_bowel', 'stomach']
device = 'cuda' if torch.cuda.is_available() else 'cpu'
lr = 0.1
momentum = 0.9
wd = 1e-4
num_epochs = 20

#  taking WandB run name input.
if wandb_enable:
  wandb_arg_name = input('Please input the WandB argument (run) name:')
  print(wandb_arg_name)

"""### 🟠 **Change the font size of the output cells (Unimportant)**"""

# print('Salam Shayan!')

# from IPython.display import HTML
# shell = get_ipython()

# def adjust_font_size():
#   display(HTML('''<style>
#     body {
#       font-size: 24px;
#     }
#   '''))

# if adjust_font_size not in shell.events.callbacks['pre_execute']:
#   shell.events.register('pre_execute', adjust_font_size)

# print('Salam Shayan!')

"""## 🟠 **Data, Loading, & Comprehension! (Very Important)**

🟡🟡🟡 *BE CAREFUL: Loading the dataset in a good way and fully comprehending it, especially in this task, is REALLY IMPORTANT. It can avoid so many future problems during training* 🟡🟡🟡

### 🟠 **Loading the Data**

### 🟡 Load and show an image
"""

img_path = r"data\train\case15\case15_day20\scans\slice_0053_266_266_1.50_1.50.png"   # let's see one image

img = Image.open(img_path)
img

# As can be seen, transformation and data comprehension is required

# This cell attempts to fully comprehend the data, its size, format, type, etc.
# This way, when we go to the rest of the project, we are less likely to go back because of data problems.
#==================================================================================

img_tensor = F.to_tensor(img)
img_tensor.shape, img_tensor.dtype, img_tensor.min(), img_tensor.max()

# 266*266 => This shows the size of the image => OK
# int32 => This is gona be problematic for now. We initially expected uint8. This is uint 32.
# Furthermore, for unint 8, 255 is the max number. We have 612 in here, clearly showing that this is not unit 8 and we must apply modifications.
# uint32 => 2**32-1 >> 612 => Now, we have found why the image is totally dark! 612 in the scale of 2**32-1 is very low and close to darkness in pixels.
# SO => modifications (normalization) is required

# function for normalization
normalizer = lambda x: (x - x.min()) / (x.max() - x.min())      # This should solve the problem of unit32

img_norm = normalizer(img_tensor)
img_norm.dtype, img_norm.min(), img_norm.max()

# type should be floar 32
# After applying normalziation, we expect 1 to be the max

plt.imshow(img_norm[0], cmap='gray')           # imag_norm => ERROR => There is a dimension in here (1) that should be removed
                                               # imag-norm[0] ~ squezze => for eliminating the first dimension
                                               # cmap = gray => for MRI , you can also use "plasma" as well
plt.axis('off');                               # removing axis

img = Image.open(img_path).convert('RGB')
img = F.to_tensor(img)
img.shape, img.dtype, img.min(), img.max()       # check for float32, 0 as min, 1 as max
                                                 # 266*266 => Image Size

"""**NOTE** => let's check one or two more image. This is to ensure we no longer have probelm with the data and we can move forward

**NOTE** => It is much easier to find the problem (somethings that require modification) right now than later when training the model.
"""

img_path = r"data\train\case34\case34_day16\scans\slice_0026_276_276_1.63_1.63.png"
img = Image.open(img_path).convert('RGB')
img

# Seems like there is still some problem

# Is is possible that conversion to RGB made the image incosistent!?
# If yes, problem must be identified and solved

img = np.array(img)                                  # Numpy array
img.shape, img.dtype, img.min(), img.max()           # min should be 0 and max should be 255
                                                     # Max is not 12220
                                                     # PROBELM?
                                                     # It converts all the numbers above 255 t0 255. So, this will happen
                                                     # This is due to using RGB without knowing the incosistency that it can cause
                                                     # We should solve this problm

# Let's use OpenCV to address the problem

img = cv2.imread(img_path, cv2.IMREAD_UNCHANGED)           # I found "IMREAD_UNCHANGED from the net"
img.shape, img.dtype, img.min(), img.max()

plt.imshow(img, cmap='gray')            # With "IMREAD_UNCHANED" the problem is solved for visualziation only
                                        # We should also normalize it later

img = normalizer(img)                                                                 # Do not forget the normalzier
print(img.dtype)                                                                      # It is still Float 64
img_tensor = torch.tensor(img, dtype=torch.float32)                                   # Should be converted to Float 32
print(img_tensor.shape, img_tensor.dtype, img_tensor.min(), img_tensor.max())         # 0 and 1 are expected for min and max
plt.imshow(img_tensor, cmap='gray')

# Important
# ==================================================
# So, check the visualization in the first place for consistency.
# Please check several images to ensure that you checked multiple images and they are right.
# Then, ensure that you normalize all the images and min and max should be (normally for medical image processing) 0 and 1
# Then, please check 0 and 1 for min and max
# They must be float 32 (should be)
# Again => Fully comprehending the data and making sure that they are OK is very important

"""### 🟡 **Load and show a segmentation mask**

"""

img_path = r"data\train\case11\case11_day0\scans\slice_0039_360_310_1.50_1.50.png"   # Make sure to use 'r'
                                                                                     # It is annoying if you don't :)
img = Image.open(img_path)
img = F.to_tensor(img)
img = normalizer(img[0])
plt.imshow(img, cmap='gray');

mask_name = 'case11_day0_slice_0039'        # The saved data for case 11.
df = pd.read_csv(r'data\train.csv')
df.head()

# Case 11 => stomach, small-bowel, large-bowl

sample = df[df['id'] == mask_name]
rle_mask = sample.iloc[2]['segmentation']    # mask
rle_mask

# Insights from the data
# Interesing!
# even numbers are small, while odd numbers are great. Why?

# Seperating small and great number
# They are saved as string, which are not suitable. They should become arrays.
# Let's set int32 so that we ensure that is supports the maximum number of great numbers (avoiding logical errors)
# They must be arrays

rle_list = rle_mask.split(' ')
starts, lengths = rle_list[::2], rle_list[1::2]
starts = np.array(starts, dtype=np.int32) - 1
lengths = np.array(lengths, dtype=np.int32)
ends = starts + lengths
starts, lengths, ends

mask = torch.zeros(img.numel(), dtype=torch.float32)     # must be Float32

for start, end in zip(starts, ends):
  mask[start:end] = 1

mask.max()    # must be 1. If otherwise, there is a problem.

mask2 = mask.reshape(img.shape)
print(mask2.shape)                          # must be 310*360 according data properties
                                            # It is very important that these must be within the same
                                            # According to data check it must 310*360

plt.imshow(img, cmap='gray')
plt.imshow(mask2, alpha=0.3);               # alpha = 0.3 => for transparency

x = torch.randint(0, 10, (3, 3))
x, x.flatten(), x.reshape(-1)

x = torch.randint(0, 10, (9,))
x, x.reshape(3, 3)

"""## 🟠 **Dataset Preparation (Very Important)**

🟠🟠🟠 *This is goning be very important part and also challenging. Consistency in data is very important* 🟠🟠🟠

### 🟡 **Load CSV file**
"""

df = pd.read_csv(os.path.join(root, 'train.csv'))      # root is defined in the arguments section at the top
                                                       # root is joined to "train.csv" with join
display(df.head())
df.shape

# Question 1 (for analysis and full comprehension)
# ===================================================================
# => How many samples do we have at max?
# at max: [115488/3]
# As can be seen, there are 3 types for each sample. Stomach and 2 bowls.
# Therefore, we maximumly have [115488/3] samples
# We can have less data as there may be NANs or NULLs as well

# We need to divied them by columns! Similar to one hot encoding. This helps for analysing the data.

df.describe()

# Data Comprehension - This is fucking importnat
# NB: Comprehending the data is crucial. You will avoid so many problme in the future
# ====================================================================================
# 115488 = 115488       => No NAN in here (there is no null values in the id part)
# 38496                 => Number of unique samples number of unique images
# 115488 / 3 = 38496    => Fortunately, we don't have a problem in this regard :)
# ====================================================================================
# 38496 - 33913 ~ 5K
# 5K less => probably for those images that have more than 1 segmentation.
# One image can have 2 or 3 segmentation obviously.
# ====================================================================================
# There are images that repeated twice! (2) => Therefore, we should remove NANs.
# Let's analyze NULL values for now

"""### 🟡 **Drop NaN values**

"""

df.dropna(inplace=True)
display(df.head())
df.shape

# 33913 => This represents all the instances that  have NAN for their segmentation masks
# inplace = True => overwrtie on the dataset
# So, we removed all the instance with NAN for their segmentation. Notably, they have overwritten.

"""### 🟡 **Find duplicate rows**

"""

# In "DESCRIBE" we have found that there are duplicated values with 2 as their frequency
# Can be related to MRI images

duplicates = df[df['segmentation'].duplicated(keep=False)]
duplicates

# Why this happened? This is why you should comprehend the data :)))
# In MRI, we analyze images through time. Images are getting captured through time and often wtih very little variations.
# Therefore, because of these very small variations, it is possible that the images (and their masks, as well) get very close to each other.
# These samples probably represents such things, which can be comprehended from their id.
# For example:
# "case133_day25_slice_0079" and "case133_day25_slice_0080" are very close. They have the same segmentation (small bowls),
# and equal masks. Therefore, they probably where captured either within the same time (twice) or very close.
# Likewise for others as well.
# The physician, who was responsible for segmentation, probably mentioned that they are equal.
# This is why it is crucail for you to comprehend the data in full.
# These masks, if they used in train and test at the same time, can represent data leakage. Therefore, they can be considered as bias!

"""### 🟡 **Create pivot table**

"""

# Pivot table is highly beneficial for us as we can put "stomach", "large-bowls", and "small-bowls" in the columns.
# This way we can use them much more conveniently. Therefore, we use pivtoal table for this task.

df = df.pivot_table(index='id', columns='class',           # classes are going to break into columns
                                values='segmentation',     # values in pivot table are segmentations
                                aggfunc='first')
df.reset_index(inplace=True)                               # in_place = True for overwriting
display(df.head())
df.shape


# This is very very good now. why?
# Because we have cleaned the data in a really good way so that it can be analyzed conveniently.
# Now, we can confidently say that we have no null values or duplications.
# Furthermore, we can confidently say that, now, each row represent one unique segmentation.
# So, we can continue with this :)

"""### 🟡 **Fill NaNs**

"""

df.fillna('', inplace=True)       # NAN => " "
df.head()

"""NOW, We should add addreeses to this DataFrame. The current dataframe is good, but more info should be added.

I want to add the address of the image to each single row so that we can have access to the image from each row.

### 🟡 **Get image paths**
"""

# import glob (in the arguments)

images_list = glob(os.path.join(root, 'train',            # go to train
                                '**',                     # This means everything - delve into everything
                                                          # ** means that there may be things in the middle. go through them
                                '*.png'),                 # This means go through all the .png files (neglect others)
                                recursive=True)           # This is very good for searching. recursive = True

len(images_list), images_list[0]

"""### 🟡 **Create a dataframe contains image paths** (better organization)

"""

comps = images_list[0].split(os.path.sep)       # Use "sep"
                                                # Use "sep" so it can be performed across different platfroms (windows / linux / etc)
print(comps)


'_'.join([comps[-3], comps[-1]]).rsplit('_', 4)[0]

image_path_list = glob(os.path.join(root, 'train',
                                           '**',
                                           '*.png'),
                       recursive=True)                            # This will results in list


# This part was really challenging. Use AI for your help, specifically splitting and organization
# ===============================================================================================
id_list = []
for i in range(0, len(image_path_list)):
  components = image_path_list[i].split(os.path.sep)[-3::2]
  id_list.append('_'.join([components[0], components[1]]).rsplit('_', 4)[0])

df_path = pd.DataFrame()
df_path['id'] = id_list
df_path['path'] = image_path_list
display(df_path.head())
df_path.shape

# Now, we have id and its correspondign path

"""### 🟡 **Merge `df` and `df_path`**

"""

df = df.merge(df_path, on='id')        # id is the same for joing
                                       # df was for segmentation masks "stomach" and 2 "bowls"
                                       # df_path is for the path of the images
                                       # They are joined based on their id
df.head()

# Let's add more info

"""### 🟡 **Augment dataFrame by adding new features**

"""

# Extract patient/case information from image identifiers.
# Example ID format: case133_day25_slice_0079
# This allows grouping MRI slices based on patient case and acquisition day.

# Extract case number from the image ID
df['case'] = df['id'].apply(
    lambda x: x.split('_')[0].replace('case', '')
)

# Extract MRI acquisition day
df['day'] = df['id'].apply(
    lambda x: int(x.split('_')[1].replace('day', ''))
)

# Extract slice number from the image identifier
df['slice'] = df['id'].apply(
    lambda x: x.split('_')[3]
)


# Extract image dimensions from the file path.
# File names contain width and height information.
# Example: xxx_256_256_xxx.png

df['width'] = df['path'].apply(
    lambda x: int(x[:-4].rsplit("_", 4)[1])
)

df['height'] = df['path'].apply(
    lambda x: int(x[:-4].rsplit("_", 4)[2])
)


# Count the number of available segmentation masks/classes.
# Columns 1 to 3 correspond to different segmentation labels.
# Empty values indicate missing annotations.

df['counts'] = np.sum(
    df.iloc[:, 1:4] != '',
    axis=1
).values


# Display the first rows to verify extracted features
display(df.head())

# Check unique numbers of available masks per image
df['counts'].unique()

# Now, we have everything. For each id, we have the segmentation mask, the path of the image, slice, day, and lenght and width of the image.
# Count represents the number of masks (annotation) in each image. It can be 1, 2 and 3. 0 are removed by ourselves.
# In data comprehnsion, we saw count = 3, for example

"""## 🟠 **Create Train, Validation, and Test Subsets from the Dataset**

#### ⚪ Train
"""

train_cases = open(os.path.join(root, 'train.txt')).read().replace('case', '').split('\n')

df_train = df[df['case'].isin(train_cases)]         # is in will return true/false and can be used.
display(df_train.head())
df_train.shape

df_train.to_csv(os.path.join(root, 'train-subset.csv'), index=False)

"""#### ⚪ Validation"""

valid_cases = open(os.path.join(root, 'validation.txt')).read().replace('case', '').split('\n')
# valid_cases

df_valid = df[df['case'].isin(valid_cases)]
display(df_valid.head())
df_valid.shape

df_valid.to_csv(os.path.join(root, 'valid-subset.csv'), index=False)

"""#### ⚪ Test"""

test_cases = open(os.path.join(root, 'test.txt')).read().replace('case', '').split('\n')
# test_cases

df_test = df[df['case'].isin(test_cases)]
display(df_test.head())
df_test.shape

df_test.to_csv(os.path.join(root, 'test-subset.csv'), index=False)

"""## 🟠 **EDA**

###### So far, we have created a very comprehensive dataframe in a good way. Now, we have a clean one that can easily be analysed.
###### We cleaned the data. We ensured that there will be no garbage input (nans, duplications, etc) that can comprimise the model performance.
###### So far, we have used pivot table to put segmentation classes (stomach, small-bowl, and large-bowl) into columns.
###### We extrated the path of the images (masks) and appended them to its correspoding image using the same id.
###### Then, we also added other data such as the length, width, count, etc for comprehensiveness.
###### Now, we have a good dataframe that can easily be analyzed and easily comprehended.
"""

df_train = pd.read_csv('data/train-subset.csv')
df_train.head()

"""### 🟡 Show an image and its mask

"""

def rle_decode(img_size, segments):
  mask = torch.zeros(3, img_size[0] * img_size[1], dtype=torch.float32)
  for i, segment in enumerate(segments):
    if str(segment) != 'nan':
      segment = segment.split()
      starts = np.array(segment[::2], dtype=np.int32) - 1
      ends = starts + np.array(segment[1::2], dtype=np.int32)
      for s, e in zip(starts, ends):
        mask[i, s:e] = 1
  return mask.reshape((3, img_size[0], img_size[1]))

train_transform = transforms.Compose([transforms.Resize((224, 224)),                                         # Resize to 224*224
                                      transforms.ToTensor(),                                                 # Tensoring
                                      transforms.Lambda(lambda x: (x - x.min()) / (x.max() - x.min())),      # Normalziation
                                      transforms.Lambda(lambda x: x.repeat(3, 1, 1))])                       # 3 channels

target_transform = transforms.Compose([transforms.Resize((224, 224))])

item = random.randint(0, df_train.shape[0])
sample = df_train.iloc[item]

img = Image.open(sample['path'])

mask = rle_decode(img.size[::-1], sample[['large_bowel', 'small_bowel', 'stomach']])     # image.size[::-1] is important
                                                                                         # this is used for the last dimension (310*360 => 360*310)

img = train_transform(img)
mask = target_transform(mask)

plt.imshow(img.permute(1, 2, 0), cmap='gray')
plt.imshow(mask.permute(1, 2, 0), alpha=0.5)                       # alph = 0.5 => for transparency
print('red: large_bowel, green: small_bowel, blue: stomach');      # which color for which part

plt.imshow(img.permute(1, 2, 0), cmap='gray')     # This is the previous image without the shown masks

img_temp = cv2.imread(sample['path'], cv2.IMREAD_UNCHANGED)       # Let's have another check with OpenCV as well
img_temp.shape, img_temp.dtype, img_temp.min(), img_temp.max()
img_temp = normalizer(img_temp)
plt.imshow(img_temp, cmap='gray')

"""### 🟡 Plot histogram of the number of samples in each class

"""

df_train.info()

df_train['counts'].value_counts().plot(kind='bar');

"""### 🟡 Plot histogram of the number of samples per case

"""

# This shows the number of samples for each case (for each person)
plt.figure(figsize=(16, 4))
df_train['case'].value_counts().plot(kind='bar');

"""### 🟡 Plot histogram of image sizes

"""

img_sizes = df_train['height'].apply(lambda x: str(x)) + 'x' + df_train['width'].apply(lambda x: str(x))
img_sizes.value_counts().plot(kind='bar');

# This helps us to comprehend the data and helps us to determine which data size is the best for resizing
# Seems like 224 is good

"""### 🟡 Calculate the total RAM occupation by dataset

"""

total_nbytes = 0

for path in df_train['path']:
  img = cv2.imread(path)
  total_nbytes += img.nbytes

print(total_nbytes/1e6)

# all images require 3GB of RAM.

120/12000       # time for loading all the data is 120sec.
                # Each data is 0.01 sec.

# In advanced works, HPC and training with parallel batches can be highly beneficial.

"""## 🟠 **Custom dataset** (use V2)"""

def rle_decode(img_size, segments):
  mask = torch.zeros(3, img_size[0] * img_size[1], dtype=torch.int32)
  for i, segment in enumerate(segments):
    if str(segment) != 'nan':
      segment = segment.split()
      starts = np.array(segment[::2], dtype=np.int32) - 1
      ends = starts + np.array(segment[1::2], dtype=np.int32)
      for s, e in zip(starts, ends):
        mask[i, s:e] = 1
  return mask.reshape((3, img_size[0], img_size[1]))

# Decodes Run-Length Encoded (RLE) segmentation masks into binary masks.
# Converts encoded pixel positions into a 3-channel tensor representing different classes.
# Returns the reconstructed mask with the original image dimensions (channels, height, width).

"""### 🟡 Pytorch V1

"""

class UWMadisonDataset(VisionDataset):

    def __init__(self, root: str, csv_file: str,
                 transform: Optional[Callable] = None,
                 target_transform: Optional[Callable] = None):

        super().__init__(root, transform=transform, target_transform=target_transform)

        self.df = pd.read_csv(os.path.join(root, csv_file))

        self.classes = ['large_bowel', 'small_bowel', 'stomach']

    def __getitem__(self, item):
        sample = self.df.iloc[item]

        img = Image.open(sample['path'])
        mask = rle_decode(img.size[::-1], sample[self.classes])

        img = self.transform(img)
        mask = self.target_transform(mask)

        return img, mask

    def __len__(self):
        return self.df.shape[0]

train_transform = transforms.Compose([transforms.Resize((224, 224)),
                                      # transforms.RandomHorizontalFlip(0.5),
                                      transforms.ToTensor(),
                                      transforms.Lambda(lambda x: (x - x.min()) / (x.max() - x.min())),
                                      transforms.Lambda(lambda x: x.repeat(3, 1, 1))])

target_transform = transforms.Compose([transforms.Resize((224, 224)),
                                      #  transforms.RandomHorizontalFlip(0.5)
                                      ])

train_set = UWMadisonDataset(root, 'train-subset.csv',
                              transform=train_transform,
                              target_transform=target_transform)

# While we must apply augmentation/transformation, the random parameter can be problemtic as it created randoness.

item = random.randint(0, len(train_set))

img, mask = train_set[item]

plt.imshow(img[0], cmap='gray')
plt.imshow(mask.permute(1, 2, 0), alpha=0.3);        ## This is problemtic as augmentation/transformation creates incosistency
                                                     ## They must be applied on train and valid at the same time. Yet,
                                                     ## Random parameter will create inconsistency

img, mask = train_set[10944]
# print(img.shape, mask.shape, [img.min().item(), img.max().item()], mask.unique())

plt.imshow(img.permute(1, 2, 0), cmap='gray')
plt.imshow(mask.permute(1, 2, 0), alpha=0.5);        ## This is problemtic as augmentation/transformation creates incosistency
                                                     ## They must be applied on train and valid at the same time. Yet,
                                                     ## Random parameter will create inconsistency

# Solution => Pytorch v2

"""### 🟡 Pytorch V2

"""

class UWMadisonDataset(VisionDataset):

    def __init__(self, root: str, csv_file: str,
                 transforms: Optional[Callable] = None):

        super().__init__(root, transforms=transforms)

        self.df = pd.read_csv(os.path.join(root, csv_file))

        self.classes = ['large_bowel', 'small_bowel', 'stomach']

    def __getitem__(self, item):
        sample = self.df.iloc[item]

        img = Image.open(sample['path'])
        mask = rle_decode(img.size[::-1], sample[self.classes])

        img = tv_tensors.Image(img)
        mask = tv_tensors.Mask(mask)

        img, mask = self.transforms(img, mask)

        return img, mask

    def __len__(self):
        return self.df.shape[0]

# attention: transformations must be applied on train and valid at the same time.
# this is very very important. If not, image and correspoding masks are not representative.

transform_train = v2.Compose([
    v2.Resize(size=(234,), antialias=True),
    v2.RandomCrop(size=(224, 224)),
    v2.RandomPhotometricDistort(p=0.5),
    v2.RandomHorizontalFlip(p=0.5),
    v2.Lambda(lambda x: (x - x.min()) / (x.max() - x.min())),
    v2.Normalize(mean=(0.5,), std=(0.5,)),
    v2.Lambda(lambda x: x.repeat(3, 1, 1)),
    ])

train_set = UWMadisonDataset(root, 'train-subset.csv',
                             transforms=transform_train)

item = random.randint(0, len(train_set))
img, mask = train_set[item]
print(img.shape, mask.shape, [img.min().item(), img.max().item()], mask.unique())

plt.imshow(img[0], cmap='gray')
plt.imshow(mask.permute(1, 2, 0), alpha=0.15);

"""### 🟡 Save Memory Option?!

"""

class UWMadisonDataset(VisionDataset):

  def __init__(self, root: str, csv_file: str,
               transforms: Optional[Callable] = None,       # from typing import Any, Callable, Dict, List, Optional, Tuple
               memory: Optional[bool] = False):

    super().__init__(root, transforms=transforms)

    self.df = pd.read_csv(os.path.join(root, csv_file))

    self.classes = ['large_bowel', 'small_bowel', 'stomach']

    self.memory = memory
    if memory:
      self._save_memory()

  def __getitem__(self, item):
    sample = self.df.iloc[item]

    img = self.imgs[item] if self.memory else self._load_image(sample['path'])
    # print(img.shape)

    mask = rle_decode(img.shape[1::], sample[self.classes])
    mask = tv_tensors.Mask(mask)

    img, mask = self.transforms(img, mask)
    return img, mask.int()

  def __len__(self):
    return self.df.shape[0]

  def _save_memory(self):
    self.imgs = []
    for path in self.df['path']:
      self.imgs.append(self._load_image(path))

  def _load_image(self, path):
    img = cv2.imread(path, cv2.IMREAD_UNCHANGED)
    img = self._minmax_scaler(img)
    return tv_tensors.Image(img)

  def _minmax_scaler(self, x):
    return np.array((x - x.min()) / (x.max() - x.min()), dtype=np.float32)

# This custom dataset class loads MRI images and their corresponding segmentation masks.
# It reads image information from a CSV file and supports optional memory loading for faster training.
# Each image mask is decoded from RLE format into three segmentation classes: large bowel, small bowel, and stomach.
# Images are normalized using Min-Max scaling and converted into TorchVision tensor formats.
# The dataset returns transformed image-mask pairs ready for deep learning segmentation models.

# attention: transformations must be applied on train and valid at the same time.
# this is very very important. If not, image and correspoding masks are not representative.
# =======================================================================================
# In Pytorch VERSION 2, augmentations can be applied to mask and image at the same time conveniently.
# You can see V2 consistently.


transform_train = v2.Compose([
    v2.Resize(size=(234,), antialias=True),
    v2.RandomCrop(size=(224, 224)),
    v2.RandomPhotometricDistort(p=0.5),
    v2.RandomHorizontalFlip(p=0.5),
    v2.Lambda(lambda x: (x - x.min()) / (x.max() - x.min())),
    v2.Normalize(mean=(0.5,), std=(0.5,)),
    v2.Lambda(lambda x: x.repeat(3, 1, 1)),
    ])

transform_eval = v2.Compose([
    v2.Resize(size=(224, 224), antialias=True),
    v2.Lambda(lambda x: (x - x.min()) / (x.max() - x.min())),
    v2.Normalize(mean=(0.5,), std=(0.5,)),
    v2.Lambda(lambda x: x.repeat(3, 1, 1)),
    ])

train_set = UWMadisonDataset(root, 'train-subset.csv', transforms=transform_train, memory=True)

valid_set = UWMadisonDataset(root, 'valid-subset.csv', transforms=transform_eval, memory=True)

test_set = UWMadisonDataset(root, 'test-subset.csv', transforms=transform_eval)

len(train_set), len(valid_set), len(test_set)

# del train_set.imgs
# del valid_set.imgs

item = random.randint(0, len(train_set))
img, mask = train_set[item]
print(img.shape, mask.shape, [img.min().item(), img.max().item()], mask.unique())

plt.imshow(img[0], cmap='gray')
plt.imshow(mask.permute(1, 2, 0), alpha=0.3);    # Problem solved

item = random.randint(0, len(test_set))
img, mask = test_set[item]
print(img.shape, mask.shape, [img.min().item(), img.max().item()], mask.unique())

plt.imshow(img[0], cmap='gray')
plt.imshow(mask.permute(1, 2, 0), alpha=0.15);       # Problem solved

"""## 🟠 **Dataloader**"""

train_loader = DataLoader(train_set, batch_size=batch_size, shuffle=True)

valid_loader = DataLoader(valid_set, batch_size=batch_size, shuffle=False)

test_loader = DataLoader(test_set, batch_size=batch_size, shuffle=False)

imgs, msks = next(iter(train_loader))
imgs.shape, msks.shape                    # 32*3*224*224 expected

def time_for_each_batch(loader):
  start = time.time()
  for iter, (img, mask) in enumerate(loader, 1):
    continue
  end = time.time()
  total_time = end - start
  return total_time, total_time/len(loader)

time_for_each_batch(valid_loader)      # 10.6 second for all valid batched. 0.23 second for each valid batch.

time_for_each_batch(test_loader)      # 57 second for all test batched. 0.6 second for each test batch.

time_for_each_batch(train_loader)     # 79.4 second for all train batched. 0.23 second for each test batch.

"""# 🔴 **Model**"""

# Semantic Segmentaiton
# Unet with good backbone
# We use "Efficient-net b1 as backbone". It is efficient. Both fast and good performance
# We can use "MobileNetV2", for instance, for faster processing. Though, it is not recommended since it is medical
# We can also use "EfficienNetB7", for instance, which is very slower but is deeper and usually result in good results.


model = smp.Unet(encoder_name=backbone,                     # in this case => efficient-net-b1
                 encoder_weights='imagenet',                # image-net is useful, though may not be optimal
                 in_channels=3,                             # in-channels = 3
                 classes=3)                                 # classes = 3 (stomach, small-bowl, large-bowl)
model

imgs, masks = next(iter(train_loader))
model(imgs).shape

start = torch.cuda.Event(enable_timing=True)
end   = torch.cuda.Event(enable_timing=True)

model = model.to(device)

start.record()
with torch.no_grad():
  out = model(imgs.to(device))
end.record()

torch.cuda.synchronize()

start.elapsed_time(end)

"""# 🔴 **Config**"""

loss_fn = smp.losses.DiceLoss(mode='multilabel')


# Dice loss is a good option. We cal alos use IoU, but I prefer DICE.
# mode = multilabel is the best option.

metric = Dice().to(device)

if wandb_enable:
    key_file = '/content/key'

    if os.path.exists(key_file):
        with open(key_file) as f:
            key = f.readline().strip()
        wandb.login(key=key)
    else:
        print("Key file does not exist. Please create the key file with your wandb API key.")

"""# 🔴 **Train ➰**

🔰 This is the template for train function, change it if needed.
"""

def train_one_epoch(model, train_loader, loss_fn, optimizer, metric, epoch=None):
  model.train()
  loss_train = MeanMetric()
  metric.reset()

  with tqdm.tqdm(train_loader, unit='batch') as tepoch:
    for inputs, targets in tepoch:
      if epoch:
        tepoch.set_description(f'Epoch {epoch}')

      inputs = inputs.to(device)
      targets = targets.to(device)

      outputs = model(inputs)

      loss = loss_fn(outputs, targets)

      loss.backward()

      optimizer.step()
      optimizer.zero_grad()

      loss_train.update(loss.item(), weight=len(targets))
      metric.update(outputs, targets)

      tepoch.set_postfix(loss=loss_train.compute().item(),
                         metric=metric.compute().item())

  return model, loss_train.compute().item(), metric.compute().item()

"""# 🔴 **Evaluation**

🔰 This is the template for evaluation function, change it if needed.
"""

def evaluate(model, test_loader, loss_fn, metric):
  model.eval()
  loss_eval = MeanMetric()
  metric.reset()

  with torch.inference_mode():
    for inputs, targets in test_loader:
      inputs = inputs.to(device)
      targets = targets.to(device)

      outputs = model(inputs)

      loss = loss_fn(outputs, targets)
      loss_eval.update(loss.item(), weight=len(targets))

      metric(outputs, targets)

  return loss_eval.compute().item(), metric.compute().item()

"""## 🔴 **Training Process 〽️**

## 🟠 **Finding Hyper-parameters**

### 🟡 **Step 1:** Calculate the loss for an untrained model using a few batches.
"""

model = smp.Unet(encoder_name=backbone, encoder_weights='imagenet', classes=num_classes).to(device)

inputs, targets = next(iter(train_loader))
inputs = inputs.to(device)
targets = targets.to(device)

with torch.no_grad():
  outputs = model(inputs)
  loss = loss_fn(outputs, targets)

print(loss)              # Initiall loss for some batches is around 0.97.

"""### 🟡 **Step 2: Try to train and overfit the model on a small subset of the dataset**"""

mini_valid_size = 500
_, mini_valid_dataset = random_split(valid_set, (len(valid_set)-mini_valid_size, mini_valid_size))
mini_valid_loader = DataLoader(mini_valid_dataset, 20, shuffle=True)

model = smp.Unet(encoder_name=backbone, encoder_weights='imagenet',
                 in_channels=3, classes=num_classes).to(device)
optimizer = torch.optim.SGD(model.parameters(), lr=0.1, momentum=0.9)
loss_fn = smp.losses.DiceLoss(mode='multilabel')

num_epochs = 50
for epoch in range(num_epochs):
  model, _, _ = train_one_epoch(model, mini_valid_loader, loss_fn, optimizer, metric, epoch+1)

torch.cuda.empty_cache()

# Use greater LR at first and then reduce it by time. Use LR scheduler.

"""### 🟡 **Step 3:Train the model for a limited number of epochs, experimenting with various learning rates.**"""

num_epochs = 3

for lr in [0.9, 0.5, 0.3, 0.1, 0.01, 0.001]:
  print(f'LR={lr}')

  model = smp.Unet(encoder_name=backbone, encoder_weights='imagenet', classes=num_classes, in_channels=3).to(device)
  optimizer = optim.SGD(model.parameters(), lr=lr, weight_decay=1e-4, momentum=0.9)

  for epoch in range(num_epochs):
    model, _, _ = train_one_epoch(model, valid_loader, loss_fn, optimizer, metric, epoch+1)

  print()

torch.cuda.empty_cache()

"""### 🟡 Step 4: Create a small grid using the weight decay and the best learning rate.




"""

# num_epochs =

# for lr in [...]:
#   for wd in [...]:
#     print(f'LR={lr}, WD={wd}')

#     model =
#     optimizer = optim.SGD(model.parameters(), lr=lr, weight_decay=wd)

#     for epoch in range(num_epochs):
#       model, loss, _ = train_one_epoch(model, train_loader, loss_fn, optimizer, epoch)

#     print()

"""### 🟡 Step 5: Train model for longer epochs using the best model from step 4.




"""

# model =

# lr =
# wd =
optimizer = optim.SGD(model.parameters(), lr=lr, weight_decay=wd, momentum=0.9, nesterov=True)

loss_train_hist = []
loss_valid_hist = []

metric_train_hist = []
metric_valid_hist = []

best_loss_valid = torch.inf
epoch_counter = 0

# num_epochs =

for epoch in range(num_epochs):
  # Train
  model, loss_train, metric_train = train_one_epoch(model,
                                                 train_set,
                                                 loss_fn,
                                                 optimizer,
                                                 metric,
                                                 epoch)
  # Validation
  loss_valid, metric_valid = evaluate(model,
                                     valid_set,
                                     loss_fn,
                                     metric)

  loss_train_hist.append(loss_train)
  loss_valid_hist.append(loss_valid)

  metric_train_hist.append(metric_train)
  metric_valid_hist.append(metric_valid)

  if loss_valid < best_loss_valid:
    torch.save(model, f'model.pt')
    best_loss_valid = loss_valid
    print('Model Saved!')

  print(f'Valid: Loss = {loss_valid:.4}, Metric = {metric_valid:.4}')
  print()

  epoch_counter += 1

"""## 🟠 **Main Loop** (with LR scheduler)"""

torch.cuda.empty_cache()

"""🔰 Define model."""

set_seed(seed)
model = model = smp.Unet(encoder_name=backbone, encoder_weights='imagenet', in_channels=3, classes=num_classes).to(device)

# model = torch.load('model.pt')

"""🔰 Define optimizer and Set learning rate and weight decay.

**MultiStepLR**
"""

set_seed(seed)
lr = 0.3
wd = 1e-4
optimizer = optim.SGD(model.parameters(), lr=lr, weight_decay=wd, momentum=0.9)
lr_scheduler = optim.lr_scheduler.MultiStepLR(optimizer, milestones=[5, 10, 15], gamma=0.1)

"""🔰 Initialize `wandb`"""

if wandb_enable:
  wandb.init(
      project=...,
      name=wandb_arg_name,
      config={
          'lr': lr,
          'momentum': momentum,
          'batch_size': batch_size,
          'seq_len': seq_len,
          'hidden_dim': hidden_dim,
          'embedding_dim': embedding_dim,
          'num_layers': num_layers,
          'dropout_embed': dropoute,
          'dropout_in_lstm': dropouti,
          'dropout_h_lstm': dropouth,
          'dropout_out_lstm': dropouto,
          'clip': clip,
      }
  )

"""🔰 Write code to train the model for `num_epochs` epoches."""

loss_train_hist = []
loss_valid_hist = []

metric_train_hist = []
metric_valid_hist = []

best_loss_valid = torch.inf
epoch_counter = 0

num_epochs = 20

for epoch in range(num_epochs):
  # Train
  model, loss_train, metric_train = train_one_epoch(model,
                                                    train_loader,
                                                    loss_fn,
                                                    optimizer,
                                                    metric,
                                                    epoch+1)
  # Validation
  loss_valid, metric_valid = evaluate(model,
                                      valid_loader,
                                      loss_fn,
                                      metric)

  loss_train_hist.append(loss_train)
  loss_valid_hist.append(loss_valid)

  metric_train_hist.append(metric_train)
  metric_valid_hist.append(metric_valid)

  if loss_valid < best_loss_valid:
    torch.save(model, f'model.pt')
    best_loss_valid = loss_valid
    print('Model Saved!')

  if wandb_enable:
    wandb.log({"metric_train": metric_train, "loss_train": loss_train,
                "metric_valid": metric_valid, "loss_valid": loss_valid})

  print(f'Valid: Loss = {loss_valid:.4}, Metric = {metric_valid:.4}, LR = {lr_scheduler.get_last_lr()[0]}')
  print()

  lr_scheduler.step()

  epoch_counter += 1

wandb.finish()

# Dice ~ 0.8 => Good results

"""## 🟠 **Plot LOSS**

🔰 Plot learning curves
"""

plt.figure(figsize=(8, 6))

plt.plot(range(epoch_counter), loss_train_hist, 'r-', label='Train')
plt.plot(range(epoch_counter), loss_valid_hist, 'b-', label='Validation')

plt.xlabel('Epoch')
plt.ylabel('loss')
plt.grid(True)
plt.legend()

"""## 🔴 **Test**"""

model_path = 'model.pt'
model = torch.load(model_path)
model.eval()

# around 33 MB

"""🔰 Test your model using data from the test set and images that are not present in the dataset."""

test_loader = DataLoader(test_set, batch_size=32)

_, metric_test = evaluate(model, test_loader, loss_fn, metric)
metric_test

"""## 🔴 **Segment**

**The optimal models could achieve 0.8 Dice on unseen data**

🔰 Your mission is to write a `segmentation` function and use a test image to see the prediction of the model.
"""

model_path = 'model.pt'
model = torch.load(model_path)
model.eval()

def segment(image, model):
  with torch.inference_mode():
    prediction = model(image)
    return torch.sigmoid(prediction).cpu()

test_loader = DataLoader(test_set, batch_size=1, shuffle=True)

img, mask = next(iter(test_loader))

output = segment(img.to(device), model)

plt.figure(figsize=(18, 6))

plt.subplot(1, 3, 1)
plt.imshow(img[0, 0], cmap='gray');
plt.title('Input')

plt.subplot(1, 3, 2)
plt.imshow(img[0, 0], cmap='gray');
plt.imshow(output[0].permute(1, 2, 0), alpha=0.3);
plt.title('Model')

plt.subplot(1, 3, 3)
plt.imshow(img[0, 0], cmap='gray');
plt.imshow(mask[0].permute(1, 2, 0).float(), alpha=0.3);
plt.title('Target');

"""## 🔴 **Experiments**"""

valid_set = UWMadisonDataset(root, 'valid-subset.csv', transforms=transform_eval)
test_set = UWMadisonDataset(root, 'test-subset.csv', transforms=transform_eval)

new_test_set = ConcatDataset([valid_set, test_set])
print(len(new_test_set))

new_test_loader = DataLoader(new_test_set, batch_size=10)

model_path = 'model.pt'
model = torch.load(model_path)
model.eval()

outputs = []

for img, mask in new_test_loader:
  output = segment(img.to(device), model)
  outputs.append(output)

"""## 🟠 **Class-wise Dice Scores**"""

large_bowel_dice, small_bowel_dice, stomach_dice = Dice(), Dice(), Dice()

for output, (_, mask) in zip(outputs, new_test_loader):
  large_bowel_dice.update(output[0, 0], mask[0, 0])
  small_bowel_dice.update(output[0, 1], mask[0, 1])
  stomach_dice.update(output[0, 2], mask[0, 2])

print(f'Large Bowel Dice: {large_bowel_dice.compute().item()}')
print(f'Small Bowel Dice: {small_bowel_dice.compute().item()}')
print(f'Stomach Dice: {stomach_dice.compute().item()}')

"""## 🟠 **Confusion Matrix**"""

tp, fp, fn, tn = smp.metrics.get_stats(outputs[-1], mask, mode='multilabel', threshold=0.5)
tp, fp, fn, tn

plt.figure(figsize=(18, 6))

plt.subplot(1, 3, 1)
plt.imshow(img[0, 0], cmap='gray');
plt.title('Input')

plt.subplot(1, 3, 2)
plt.imshow(img[0, 0], cmap='gray');
plt.imshow(output[0].permute(1, 2, 0), alpha=0.3);
plt.title('Model')

plt.subplot(1, 3, 3)
plt.imshow(img[0, 0], cmap='gray');
plt.imshow(mask[0].permute(1, 2, 0).float(), alpha=0.3);
plt.title('Target');

imgs, masks = next(iter(new_test_loader))

outputs = segment(imgs.to(device), model)

tp, fp, fn, tn = smp.metrics.get_stats(outputs[[-1]], masks[[-1]], mode='multilabel', threshold=0.5)
tp#, fp, fn, tn

outputs[0].shape

smp.metrics.accuracy(tp, fp, fn, tn)

stat_scores = tm.StatScores(task='multilabel', num_labels=3, average=None)
stat_scores.update(outputs[[-1]], masks[[-1]])
stat_scores.compute()

# done